---

- name: ensure html directory exist
  file:
        path: "{{ data_dir }}"
        state: directory
        mode: 0755
        
- name: add  index.html
  template:
        src: index.html.j2
        dest: "{{ data_dir }}/index.html"
