---
- hosts: front
  become: yes
  vars:
    - nginx_version: nginx=1.14.0-0ubuntu1.5
    - success_message: "Nginx version {{ nginx_version }} installed successfully"
  tasks:
    - name: Install the Nginx HTTP Server
      apt: 
        name: "{{ nginx_version }}"
        update_cache: yes 
        state: present

    - debug:
        msg: "{{ success_message }}"
