---
- name: Nginx - Install the package CentOS 7
  yum:
    name: "{{nginx_pkgs}}"
    state: latest
    update_cache: yes
  when:  ansible_distribution_major_version == "7"

- name: Nginx - Install the package CentOS (othen than 7)
  yum:
    name: "{{nginx_pkgs}}"
    state: latest
    update_cache: yes
  when:  ansible_distribution_major_version != "7"


