---

- name: Apache - Install - Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


- name: Apache - Install - Define apache_package.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined


- name: Apache - Install - Setup apache for {{ ansible_os_family }}
  include_tasks: "install_{{ ansible_os_family }}.yml"




